displayName=Exact Stacks
author=robisa693
description=Shows exact coin stack values broken down by denomination (b/m/k/gp). Optionally works for any stackable item.
tags=exact,stacks,coins,gp,value,quantity,count,breakdown,denominations,stackable,money,cash,wealth
plugins=com.robisa693.exactstacks.StackBreakdownPlugin
